Tutorial_73: 73-Multifile_Compilation.o 73.2.o
	g++ 73-Multifile_Compilation.o 73.2.o -o Tutorial_73

73-Multifile_Compilation.o: 73-Multifile_Compilation.cpp
	g++ -c 73-Multifile_Compilation.cpp

73.2.o: 73.2.cpp
	g++ -c 73.2.cpp

clean:
	rm *.o math